name: Verify SLSA Level 1 Policy

on:
  # schedule:
  #    - cron:  '0 * * * *'
  workflow_dispatch:
env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
  AUTHOR_NAME: Jane Doe
  AUTHOR_EMAIL: info@scribesecurity.com
  AUTHOR_PHONE: 111-1111-11
  SUPPLIER_NAME: Scribe-Security
  SUPPLIER_URL: www.scribesecurity.com
  SUPPLIER_EMAIL: info@scribesecurity.com
  SUPPLIER_PHONE: 001-001-0011
  USER_DATA: service-binding
  PRODUCT_VERSION: "9"
  PRODUCT_NAME: Scribe-Synthetic-Testing
  COMPANY_CA: ${{ secrets.COMPANY_CA }}
  SIGNER_CERT: ${{ secrets.SIGNER_CERT }}
  SIGNER_KEY: ${{ secrets.SIGNER_KEY }}
  API: ${{ secrets.api }}

jobs:
  verify-policy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify SLSA Level 1
        id: slsa_ver1
        uses: scribe-security/action-verify@master
        with:
          target: 'docker:github-action:${{ github.sha }}'
          scribe-enable: true
          product-key: "Rahul"
          product-version: ${{ env.PRODUCT_VERSION }}
          scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
          format: attest
          config: .valint.yaml
          rule: slsa/l1-provenance-exists@v1
          verbose: 2
