name: SLSA Compliance Workflow

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
  APP_NAME: Scribe-Synthetic-Testing
  PRODUCT_VERSION: "9"
  COMPANY_CA: ${{ secrets.COMPANY_CA }}
  SIGNER_CERT: ${{ secrets.SIGNER_CERT }}
  SIGNER_KEY: ${{ secrets.SIGNER_KEY }}

jobs:
  # Step 1-a: Generate Signed SBOM for Docker Image
  image-attest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate signed SBOM for docker image
        uses: scribe-security/action-bom@master
        with:
          target: 'docker:github-action:${{ github.sha }}'
          scribe-enable: true
          product-key: "Rahul"
          product-version: ${{ env.PRODUCT_VERSION }}
          scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
          format: attest
          config: .valint.yaml

  # Step 1-b: Generate SLSA Provenance Record
  generate-provenance:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create SLSA provenance
        id: slsa_provenance
        uses: scribe-security/action-slsa@master
        with:
          target: 'docker:github-action:${{ github.sha }}'
          scribe-enable: true
          product-key: "Rahul"
          product-version: "6"
          scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
          format: attest
          config: .valint.yaml

  # Step 2a: Verify SLSA Level 1 Policy
  verify-slsa-l1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify SLSA Level 1
        id: slsa_ver1
        uses: scribe-security/action-verify@master
        with:
          target: 'docker:github-action:${{ github.sha }}'
          scribe-enable: true
          product-key: "Rahul"
          product-version: ${{ env.PRODUCT_VERSION }}
          scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
          format: attest
          config: .valint.yaml
          rule: slsa/l1-provenance-exists@v1
          verbose: 2

  # Step 2b: Verify SLSA Level 2 Policy
  verify-slsa-l2:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify SLSA Level 2
        id: slsa_ver2
        uses: scribe-security/action-verify@master
        with:
          target: 'docker:github-action:${{ github.sha }}'
          scribe-enable: true
          product-key: "Rahul"
          product-version: ${{ env.PRODUCT_VERSION }}
          scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
          format: attest
          config: .valint.yaml
          rule: slsa/l2-provenance-authenticated@v1
          verbose: 2
