name: Verify SLSA Level 1 Policy

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}

jobs:
  verify-policy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/scribe-training-app:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/scribe-training-app:${{ github.sha }}

      - name: Verify SLSA Level 1
        id: slsa_ver1
        uses: scribe-security/action-verify@master
        with:
          target: ${{ secrets.DOCKER_USERNAME }}/scribe-training-app:${{ github.sha }}
          scribe-enable: true
          product-key: "Rahul"
          product-version: ${{ env.PRODUCT_VERSION }}
          scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
          format: attest
          config: .valint.yaml
          rule: slsa/l1-provenance-exists@v1
          verbose: 2
