name: SLSA Compliance Workflow

on:
  workflow_run:
        workflows: ['Scribetest-create-signed-git-commit-sbom.yml']
        types: [completed]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
  AUTHOR_NAME: Jane Doe
  AUTHOR_EMAIL: info@scribesecurity.com
  AUTHOR_PHONE: 111-1111-11
  SUPPLIER_NAME: Scribe-Security
  SUPPLIER_URL: www.scribesecurity.com
  SUPPLIER_EMAIL: info@scribesecurity.com
  SUPPLIER_PHONE: 001-001-0011
  USER_DATA: service-binding
  PRODUCT_NAME: Scribe-Synthetic-Testing
  PRODUCT_VERSION: "6"
  COMPANY_CA: ${{ secrets.COMPANY_CA }}
  SIGNER_CERT: ${{ secrets.SIGNER_CERT }}
  SIGNER_KEY: ${{ secrets.SIGNER_KEY }}

jobs:
  # Step 1-a: Generate Signed SBOM for Docker Image
  image-attest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate signed SBOM for repository content
        uses: scribe-security/action-bom@master
        with:
          target: 'git:.'
          scribe-enable: true
          components: commits,packages,files,dep
          product-key: "Shivam1"
          product-version: ${{ env.PRODUCT_VERSION }}
          scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
          format: attest
          author-name: ${{ env.AUTHOR_NAME }}
          author-email: ${{ env.AUTHOR_EMAIL }}
          author-phone: ${{ env.AUTHOR_PHONE }}
          supplier-name: ${{ env.SUPPLIER_NAME }}
          supplier-url: ${{ env.SUPPLIER_URL }}
          supplier-email: ${{ env.SUPPLIER_EMAIL }}
          supplier-phone: ${{ env.SUPPLIER_PHONE }}

      - name: Build the Docker image
        id: valint_attest_slsa_master
        run: docker build . -t github-action:${{ github.sha }}

      - name: Generate signed SBOM for Docker image
        uses: scribe-security/action-bom@master
        with:
          target: 'docker:github-action:${{ github.sha }}'
          scribe-enable: true
          components: commits,packages,files,dep
          product-key: "Shivam1"
          product-version: ${{ env.PRODUCT_VERSION }}
          scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
          format: attest
          force: true
          config: .valint.yaml
          author-name: ${{ env.AUTHOR_NAME }}
          author-email: ${{ env.AUTHOR_EMAIL }}
          author-phone: ${{ env.AUTHOR_PHONE }}
          supplier-name: ${{ env.SUPPLIER_NAME }}
          supplier-url: ${{ env.SUPPLIER_URL }}
          supplier-email: ${{ env.SUPPLIER_EMAIL }}
          supplier-phone: ${{ env.SUPPLIER_PHONE }}

  # Step 1-b: Generate SLSA Provenance Record
  generate-provenance:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      #packages: write
      id-token: write

    steps:
      - name:  Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build the Docker image
        run: docker build . -t github-action:${{ github.sha }}

      - name: Generate SLSA provenance
        id: slsa_provenance
        uses: scribe-security/action-slsa@master
        with:
          target: 'docker:github-action:${{ github.sha }}'
          scribe-enable: true
          product-key: "Shivam1"
          product-version: ${{ env.PRODUCT_VERSION }}
          scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
          format: attest-slsa
          force: true
          config: .valint.yaml
          author-name: ${{ env.AUTHOR_NAME }}
          author-email: ${{ env.AUTHOR_EMAIL }}
          author-phone: ${{ env.AUTHOR_PHONE }}
          supplier-name: ${{ env.SUPPLIER_NAME }}
          supplier-url: ${{ env.SUPPLIER_URL }}
          supplier-email: ${{ env.SUPPLIER_EMAIL }}
          supplier-phone: ${{ env.SUPPLIER_PHONE }}

  # Step 2a: Verify SLSA Level 1 Policy
  verify-slsa-l1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      #packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build the Docker image
        run: docker build . -t github-action:${{ github.sha }}

      - name: Verify SLSA Level 1
        uses: scribe-security/action-verify@master
        with:
          target: 'docker:github-action:${{ github.sha }}'
          scribe-enable: true
          product-key: "Shivam1"
          product-version: ${{ env.PRODUCT_VERSION }}
          scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
          format: attest
          config: .valint.yaml
          #rule: slsa/l1-provenance-exists@v1
          #verbose: 2

  # Step 2b: Verify SLSA Level 2 Policy
  verify-slsa-l2:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      #packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build the Docker image
        run: docker build . -t github-action:${{ github.sha }}

      - name: Verify SLSA Level 2
        uses: scribe-security/action-verify@master
        with:
          target: 'docker:github-action:${{ github.sha }}'
          scribe-enable: true
          product-key: "Shivam1"
          product-version: ${{ env.PRODUCT_VERSION }}
          scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
          format: attest
          config: .valint.yaml
          rule: slsa/l2-provenance-authenticated@v1
          verbose: 2

      - uses: actions/upload-artifact@v4
        with:
          name: provenance
          path: ${{ steps.valint_attest_slsa_master.outputs.OUTPUT_PATH }}