name: Verify SLSA Level 1 Policy

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
  AUTHOR_NAME: Jane Doe
  AUTHOR_EMAIL: info@scribesecurity.com
  PRODUCT_VERSION: "9"
  PRODUCT_NAME: Scribe-Synthetic-Testing
  COMPANY_CA: ${{ secrets.COMPANY_CA }}
  SIGNER_CERT: ${{ secrets.SIGNER_CERT }}
  SIGNER_KEY: ${{ secrets.SIGNER_KEY }}
  API: ${{ secrets.api }}

jobs:
  verify-policy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify SLSA Level 1
        id: slsa_ver1
        uses: scribe-security/action-verify@master
        with:
          target: ${{ secrets.DOCKER_USERNAME }}/scribe-training-app:${{ github.sha }}-${{ github.run_number }}
          scribe-enable: true
          product-key: ${{ env.PRODUCT_NAME }}
          product-version: ${{ env.PRODUCT_VERSION }}
          scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
          format: attest
          config: .valint.yaml
          rule: slsa/l1-provenance-exists@v1
          verbose: 3
